// <auto-generated>
// Generated by CurrencyManager
// </auto-generated>

using GameMaker.Core.Runtime;

namespace GameMaker.Core.Runtime
{
   public class Currency
    {
        public class Coin
         {
            public const string ID = "Coin";

             public static CurrencyDefinition GetDefinition()
             {
                 return CurrencyManager.Instance.GetDefinition(ID);
             }
          }

        public class Gem
         {
            public const string ID = "Gem";

             public static CurrencyDefinition GetDefinition()
             {
                 return CurrencyManager.Instance.GetDefinition(ID);
             }
          }

        public class Cash
         {
            public const string ID = "Cash";

             public static CurrencyDefinition GetDefinition()
             {
                 return CurrencyManager.Instance.GetDefinition(ID);
             }
          }

    }
}
