// <auto-generated>
// Generated by CurrencyManager
// </auto-generated>

using GameMaker.Core.Runtime;

namespace GameMaker.Core.Runtime
{
   public class Property
    {
    public class Level
    {
        public const string ID = "Level";

        public static StatDefinition GetDefinition()
        {
            return PropertyManager.Instance.GetDefinition(ID) as StatDefinition;
        }
    }
    }
}
